### ISSUE TITLE
Implement Book Entity

### ISSUE THREAD

**Issue by EmranJadidi76** [mehran3100/book-management#1]
Create the Book entity to represent books in the system. This entity should include the necessary attributes and relationships to store and manage book data effectively.

Property suggestion

id (Primary Key): A unique identifier for each book.
title: The title of the book.
author: The name(s) of the author(s).
publicationDate: The date the book was published.
isbn: The ISBN number of the book.
price: The price of the book.
genre: The genre or category of the book.

**Comment by mehran3100** [comment]
added category and genre entities and added them into book entity with proper relations and methods
