### ISSUE TITLE
Implement Author Entity

### ISSUE THREAD

**Issue by EmranJadidi76** [mehran3100/book-management#2]
Develop the Author entity to represent authors in the system. This entity should store essential and optional details about authors, enabling effective management and association with books or other content in the system.

Property suggestion

Basic Information:

id (Primary Key): A unique identifier for each author.
firstName: The author's first name.
lastName: The author's last name.
dateOfBirth: The date of birth of the author.
nationality: The nationality or country of origin.
biography: A brief description of the author's life and works.

Contact Information:

email (Optional): Contact email for the author (if applicable).
website (Optional): URL of the author's official website or profile.
Professional Details:

awards: List of awards the author has received (if applicable).
genres: List of genres the author specializes in (e.g., Fiction, Science, Biography).
publishedBooksCount: The total number of books published by the author (if applicable).
Relationships:

Books: Define a one-to-many relationship with the Book entity.
Publisher (Optional): A many-to-one relationship if a publisher entity exists.

**Comment by mehran3100** [comment]
Implemented Author, Contact and Address
